/*
    VPS2.h
    Generated by FMOD Designer v4.34.3 
*/

#ifndef VPS2_H
#define VPS2_H

/*
    Total number of events in the project
*/
const int EVENTCOUNT_VPS2 = 6;

/*
    EventGroup/Event-relative indices
*/
const int EVENTGROUP_VPS2_VPS2 = 0;
const int EVENTGROUPCOUNT_VPS2_VPS2 = 6;
const int EVENT_VPS2_VPS2_BOUNCYBALL = 0;
const int EVENT_VPS2_VPS2_FLIPPER = 1;
const int EVENT_VPS2_VPS2_ROLLOVER = 2;
const int EVENT_VPS2_VPS2_STARTUP = 3;
const int EVENT_VPS2_VPS2_DINGS = 4;
const int EVENT_VPS2_VPS2_MESSAGE = 5;

/*
    Project-unique event ids
*/
const int EVENTID_VPS2_VPS2_BOUNCYBALL = 0;
const int EVENTID_VPS2_VPS2_FLIPPER = 1;
const int EVENTID_VPS2_VPS2_ROLLOVER = 2;
const int EVENTID_VPS2_VPS2_STARTUP = 3;
const int EVENTID_VPS2_VPS2_DINGS = 4;
const int EVENTID_VPS2_VPS2_MESSAGE = 5;

const int EVENTCATEGORY_VPS2_MASTER = 0;
const int EVENTCATEGORYCOUNT_VPS2_MASTER = 6;

const int EVENTCATEGORY_VPS2_MASTER_MUSIC = 0;
const int EVENTCATEGORYCOUNT_VPS2_MASTER_MUSIC = 0;


/*
    Event GUIDs
*/
const char *EVENTGUID_VPS2_VPS2_BOUNCYBALL = "{40fd1b71-304f-4263-8ce4-14c7322d682d}";
const char *EVENTGUID_VPS2_VPS2_FLIPPER = "{5e4cdfb0-d58f-4c11-998f-eb0a34dbba78}";
const char *EVENTGUID_VPS2_VPS2_ROLLOVER = "{3c9783cf-7f37-4550-a629-c9c598e493ba}";
const char *EVENTGUID_VPS2_VPS2_STARTUP = "{8d4446be-a338-44bb-b2af-2e3e90558285}";
const char *EVENTGUID_VPS2_VPS2_DINGS = "{c6c973d9-9502-4f92-96d2-2252774df4f2}";
const char *EVENTGUID_VPS2_VPS2_MESSAGE = "{9af2d3b9-c4e7-47a2-b80e-053440b6d343}";

/*
    Music parameter ids
*/
const unsigned int MUSICPARAM_VPS2_BASSSEQUENCE = 1;

/*
    Music cue ids
*/
const unsigned int MUSICCUE_VPS2_DRLOOP1 = 2;
const unsigned int MUSICCUE_VPS2_DRLOOP2 = 3;
const unsigned int MUSICCUE_VPS2_DRLOOP3 = 4;
const unsigned int MUSICCUE_VPS2_ANDROID = 7;
const unsigned int MUSICCUE_VPS2_BASS = 8;

/*
    Music segment ids
*/
const unsigned int MUSICSEGMENT_VPS2_DRLOOP1_THEME_DRLOOP1 = 20;
const unsigned int MUSICSEGMENT_VPS2_DRLOOP2_THEME_DRLOOP2 = 21;
const unsigned int MUSICSEGMENT_VPS2_DRLOOP3_THEME_DRLOOP3 = 22;
const unsigned int MUSICSEGMENT_VPS2_BASS_THEME_BASS1 = 43;
const unsigned int MUSICSEGMENT_VPS2_BASS_THEME_BASS2 = 44;
const unsigned int MUSICSEGMENT_VPS2_BASS_THEME_BASS3 = 45;
const unsigned int MUSICSEGMENT_VPS2_BASS_THEME_BASS4 = 46;
const unsigned int MUSICSEGMENT_VPS2_BASS_THEME_BASS5 = 47;
const unsigned int MUSICSEGMENT_VPS2_ANDROID_THEME_ANDROID1 = 48;

#endif /* VPS2_H */
